version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: reserve-me-postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
